version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis
    volumes:
      - ./var/docker/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
